sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - cmake
      - cmake-data
      - g++-7
      - libboost1.55-all-dev
      - valgrind
      - libssl-dev


before_install:
  - git clone https://github.com/Grauniad/CMakeUtils.git
  - export CXX="g++-7"
  - export CC="gcc-7"
  - g++-7 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls

script:
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cat Testing/Temporary/MemoryChecker.*.log
  - cd ..
  - ./CMakeUtils/travis/doCoverage.sh
