sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - cmake
      - cmake-data
      - g++-9
      - libboost-all-dev
      - valgrind
      - libssl-dev


before_install:
  - git clone https://github.com/Grauniad/CMakeUtils.git
  - export CXX="g++-9"
  - export CC="gcc-9"
  - g++-9 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls

script:
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cat Testing/Temporary/*.log
  - cd ..
  - GCOV=gcov=-9 ./CMakeUtils/travis/doCoverage.sh
